language: python
build:
  image: qarium/goga-python-3.12:1.0
  task_executor:
    agent: claude
    env:
      ANTHROPIC_DEFAULT_HAIKU_MODEL: "glm-4.7"
      ANTHROPIC_DEFAULT_SONNET_MODEL: "glm-5-turbo"
      ANTHROPIC_DEFAULT_OPUS_MODEL: "glm-5.1"
      ANTHROPIC_BASE_URL: "https://api.z.ai/api/anthropic"
codemanifest:
  usages:
    conventions: .goga/usages/conventions.md
  annotations: |
    Use `conventions` for code writing rules and testing.
